"""initial schema

Revision ID: 1168dd72adaf
Revises: 
Create Date: 2026-08-30 19:56:37.541916
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '1168dd72adaf'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deletion_receipt',
    sa.Column('notification_id', sa.String(length=200), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=True),
    sa.Column('user_id', sa.String(length=200), nullable=True),
    sa.Column('eias_token', sa.String(length=200), nullable=True),
    sa.Column('listings_deleted', sa.Integer(), nullable=False),
    sa.Column('observations_deleted', sa.Integer(), nullable=False),
    sa.Column('unmatched', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_table('item_spec',
    sa.Column('title_hash', sa.String(length=64), nullable=False),
    sa.Column('normalized_title', sa.String(length=500), nullable=False),
    sa.Column('capacity_per_module_gb', sa.Integer(), nullable=True),
    sa.Column('module_count', sa.Integer(), nullable=True),
    sa.Column('total_gb', sa.Integer(), nullable=True),
    sa.Column('ddr_gen', sa.String(length=10), nullable=True),
    sa.Column('speed_mt', sa.Integer(), nullable=True),
    sa.Column('form_factor', sa.String(length=20), nullable=True),
    sa.Column('rank_org', sa.String(length=20), nullable=True),
    sa.Column('ecc', sa.Boolean(), nullable=True),
    sa.Column('registered', sa.Boolean(), nullable=True),
    sa.Column('method', sa.Enum('REGEX', 'LLM', 'MANUAL', name='extractionmethod', native_enum=False, length=32), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('model_id', sa.String(length=100), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('corrected_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('title_hash')
    )
    op.create_table('listing',
    sa.Column('item_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('title_hash', sa.String(length=64), nullable=False),
    sa.Column('seller_username', sa.String(length=200), nullable=True),
    sa.Column('seller_user_id', sa.String(length=200), nullable=True),
    sa.Column('seller_eias_token', sa.String(length=200), nullable=True),
    sa.Column('condition', sa.String(length=100), nullable=True),
    sa.Column('condition_id', sa.String(length=20), nullable=True),
    sa.Column('buying_option', sa.Enum('FIXED_PRICE', 'AUCTION', 'BEST_OFFER', 'CLASSIFIED_AD', 'OTHER', name='buyingoption', native_enum=False, length=32), nullable=False),
    sa.Column('item_web_url', sa.String(length=1000), nullable=True),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('category_id', sa.String(length=50), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index(op.f('ix_listing_condition_id'), 'listing', ['condition_id'], unique=False)
    op.create_index(op.f('ix_listing_seller_eias_token'), 'listing', ['seller_eias_token'], unique=False)
    op.create_index(op.f('ix_listing_seller_user_id'), 'listing', ['seller_user_id'], unique=False)
    op.create_index(op.f('ix_listing_seller_username'), 'listing', ['seller_username'], unique=False)
    op.create_index(op.f('ix_listing_title_hash'), 'listing', ['title_hash'], unique=False)
    op.create_table('query',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('q', sa.String(length=500), nullable=False),
    sa.Column('category_ids', sa.String(length=200), nullable=True),
    sa.Column('filter_expr', sa.String(length=1000), nullable=True),
    sa.Column('marketplace_id', sa.String(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('cadence_minutes', sa.Integer(), nullable=False),
    sa.Column('scan_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_scanned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_pages', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('rate_budget',
    sa.Column('day', sa.String(length=10), nullable=False),
    sa.Column('calls_used', sa.Integer(), nullable=False),
    sa.Column('calls_limit', sa.Integer(), nullable=False),
    sa.Column('last_authoritative_read', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_authoritative_remaining', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('day')
    )
    op.create_table('listing_disappearance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_item_id', sa.String(length=100), nullable=False),
    sa.Column('query_id', sa.Integer(), nullable=False),
    sa.Column('cohort_key', sa.String(length=300), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('last_total_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['query.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listing_disappearance_cohort_key'), 'listing_disappearance', ['cohort_key'], unique=False)
    op.create_index(op.f('ix_listing_disappearance_listing_item_id'), 'listing_disappearance', ['listing_item_id'], unique=False)
    op.create_table('scan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('RUNNING', 'COMPLETE', 'FAILED', 'SKIPPED_BUDGET', name='scanstatus', native_enum=False, length=32), nullable=False),
    sa.Column('api_calls', sa.Integer(), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('capped', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['query_id'], ['query.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scan_query_started', 'scan', ['query_id', 'started_at'], unique=False)
    op.create_table('watch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.String(length=100), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.item_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('listing_id')
    )
    op.create_table('deal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.String(length=100), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('cohort_key', sa.String(length=300), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('per_gb', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('cohort_p10', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('cohort_n', sa.Integer(), nullable=False),
    sa.Column('score', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('flagged_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.item_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['scan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('listing_id', name='uq_deal_listing')
    )
    op.create_index(op.f('ix_deal_cohort_key'), 'deal', ['cohort_key'], unique=False)
    op.create_index(op.f('ix_deal_listing_id'), 'deal', ['listing_id'], unique=False)
    op.create_table('listing_observation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.String(length=100), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('shipping_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.item_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['scan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('listing_id', 'scan_id', name='uq_observation_listing_scan')
    )
    op.create_index(op.f('ix_listing_observation_listing_id'), 'listing_observation', ['listing_id'], unique=False)
    op.create_index(op.f('ix_listing_observation_scan_id'), 'listing_observation', ['scan_id'], unique=False)
    op.create_table('scan_aggregate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('query_id', sa.Integer(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cohort_key', sa.String(length=300), nullable=False),
    sa.Column('n', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('price_min', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('price_p10', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('price_p25', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('price_median', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('price_mean', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('per_gb_min', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('per_gb_p10', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('per_gb_p25', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('per_gb_median', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('per_gb_mean', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['query_id'], ['query.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['scan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scan_id', 'cohort_key', name='uq_aggregate_scan_cohort')
    )
    op.create_index('ix_aggregate_cohort_time', 'scan_aggregate', ['cohort_key', 'observed_at'], unique=False)
    op.create_index(op.f('ix_scan_aggregate_cohort_key'), 'scan_aggregate', ['cohort_key'], unique=False)
    op.create_index(op.f('ix_scan_aggregate_observed_at'), 'scan_aggregate', ['observed_at'], unique=False)
    op.create_index(op.f('ix_scan_aggregate_query_id'), 'scan_aggregate', ['query_id'], unique=False)
    op.create_index(op.f('ix_scan_aggregate_scan_id'), 'scan_aggregate', ['scan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scan_aggregate_scan_id'), table_name='scan_aggregate')
    op.drop_index(op.f('ix_scan_aggregate_query_id'), table_name='scan_aggregate')
    op.drop_index(op.f('ix_scan_aggregate_observed_at'), table_name='scan_aggregate')
    op.drop_index(op.f('ix_scan_aggregate_cohort_key'), table_name='scan_aggregate')
    op.drop_index('ix_aggregate_cohort_time', table_name='scan_aggregate')
    op.drop_table('scan_aggregate')
    op.drop_index(op.f('ix_listing_observation_scan_id'), table_name='listing_observation')
    op.drop_index(op.f('ix_listing_observation_listing_id'), table_name='listing_observation')
    op.drop_table('listing_observation')
    op.drop_index(op.f('ix_deal_listing_id'), table_name='deal')
    op.drop_index(op.f('ix_deal_cohort_key'), table_name='deal')
    op.drop_table('deal')
    op.drop_table('watch')
    op.drop_index('ix_scan_query_started', table_name='scan')
    op.drop_table('scan')
    op.drop_index(op.f('ix_listing_disappearance_listing_item_id'), table_name='listing_disappearance')
    op.drop_index(op.f('ix_listing_disappearance_cohort_key'), table_name='listing_disappearance')
    op.drop_table('listing_disappearance')
    op.drop_table('rate_budget')
    op.drop_table('query')
    op.drop_index(op.f('ix_listing_title_hash'), table_name='listing')
    op.drop_index(op.f('ix_listing_seller_username'), table_name='listing')
    op.drop_index(op.f('ix_listing_seller_user_id'), table_name='listing')
    op.drop_index(op.f('ix_listing_seller_eias_token'), table_name='listing')
    op.drop_index(op.f('ix_listing_condition_id'), table_name='listing')
    op.drop_table('listing')
    op.drop_table('item_spec')
    op.drop_table('deletion_receipt')
    # ### end Alembic commands ###
