"""drop seller identifiers; deletion receipt holds no personal data

Revision ID: 1855f727980e
Revises: 1168dd72adaf
Create Date: 2026-08-30 21:45:37.279520
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '1855f727980e'
down_revision: str | None = '1168dd72adaf'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Remove every column that could hold an eBay user identifier.

    NOTE for anyone running this against a database that actually held seller
    data: `DROP COLUMN` in Postgres is a catalog change. The bytes remain in the
    heap pages until those pages are rewritten, so the values are still
    recoverable from the data files afterwards. Run `VACUUM FULL listing;` (and
    allow WAL to rotate) before claiming the data is gone.

    That did not apply when this migration was written — touchstone had never
    connected to eBay, so no real seller value was ever stored.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deletion_receipt', sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('deletion_receipt', 'unmatched')
    op.drop_column('deletion_receipt', 'completed_at')
    op.drop_column('deletion_receipt', 'user_id')
    op.drop_column('deletion_receipt', 'username')
    op.drop_column('deletion_receipt', 'listings_deleted')
    op.drop_column('deletion_receipt', 'observations_deleted')
    op.drop_column('deletion_receipt', 'eias_token')
    op.drop_index(op.f('ix_listing_seller_eias_token'), table_name='listing')
    op.drop_index(op.f('ix_listing_seller_user_id'), table_name='listing')
    op.drop_index(op.f('ix_listing_seller_username'), table_name='listing')
    op.drop_column('listing', 'seller_user_id')
    op.drop_column('listing', 'seller_eias_token')
    op.drop_column('listing', 'seller_username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listing', sa.Column('seller_username', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('listing', sa.Column('seller_eias_token', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('listing', sa.Column('seller_user_id', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_listing_seller_username'), 'listing', ['seller_username'], unique=False)
    op.create_index(op.f('ix_listing_seller_user_id'), 'listing', ['seller_user_id'], unique=False)
    op.create_index(op.f('ix_listing_seller_eias_token'), 'listing', ['seller_eias_token'], unique=False)
    op.add_column('deletion_receipt', sa.Column('eias_token', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('deletion_receipt', sa.Column('observations_deleted', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('deletion_receipt', sa.Column('listings_deleted', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('deletion_receipt', sa.Column('username', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('deletion_receipt', sa.Column('user_id', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('deletion_receipt', sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('deletion_receipt', sa.Column('unmatched', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('deletion_receipt', 'acknowledged_at')
    # ### end Alembic commands ###
