"""seller feedback floor

Revision ID: 59e51e06e599
Revises: 1855f727980e
Create Date: 2026-08-30 21:58:54.106431
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '59e51e06e599'
down_revision: str | None = '1855f727980e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Add the seller-feedback floor.

    Two adjustments to what autogenerate produced:

    1. `nullable=False` with no default fails outright on a table that already has
       rows. Every column gets a server_default.

    2. The backfills deliberately differ. New queries adopt the floor of 1, which
       is the behaviour going forward. Existing *scans* are backfilled with 0,
       because they ran before the filter existed and no listing was excluded from
       them — stamping them with 1 would make the historical series claim a
       population it never sampled, which is precisely the discontinuity this
       column exists to make visible.
    """
    op.add_column(
        "query",
        sa.Column(
            "min_seller_feedback", sa.Integer(), nullable=False, server_default="1"
        ),
    )
    op.add_column(
        "scan",
        sa.Column(
            "min_seller_feedback", sa.Integer(), nullable=False, server_default="0"
        ),
    )
    op.add_column(
        "scan",
        sa.Column(
            "excluded_low_feedback", sa.Integer(), nullable=False, server_default="0"
        ),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scan', 'excluded_low_feedback')
    op.drop_column('scan', 'min_seller_feedback')
    op.drop_column('query', 'min_seller_feedback')
    # ### end Alembic commands ###
