"""record the seller exclusion list in force per scan

Revision ID: 6a392d4d32e4
Revises: 7ac4e12b9f03
Create Date: 2026-08-31 08:26:58.822093
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '6a392d4d32e4'
down_revision: str | None = '7ac4e12b9f03'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # server_default is required, not cosmetic: `scan` already has rows, and a
    # NOT NULL column with no default cannot be added to a populated table.
    #
    # Zero is the correct value for those rows rather than a convenient one. No
    # exclusion list existed before this migration, so no scan before it excluded
    # anybody, and the null digest says the same thing. Backfilling any other value
    # would invent a discontinuity in the trend that never happened.
    op.add_column(
        'scan',
        sa.Column(
            'excluded_sellers_count', sa.Integer(), nullable=False, server_default='0'
        ),
    )
    op.add_column(
        'scan', sa.Column('excluded_sellers_digest', sa.String(length=32), nullable=True)
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scan', 'excluded_sellers_digest')
    op.drop_column('scan', 'excluded_sellers_count')
    # ### end Alembic commands ###
